#ifndef GROWING_MACROS_H
#define GROWING_MACROS_H

#define GROWING_STRINGIFY(S) GROWING_STRINGIFY_(S)
#define GROWING_STRINGIFY_(S) #S

#define GROWING_CONCAT(A, B) GROWING_CONCAT_(A, B)
#define GROWING_CONCAT_(A, B) A##B

#define GROWING_ABI_VERSION_NO 1
#define GROWING_VERSION "1.0.0"
#define GROWING_VERSION_MAJOR 1
#define GROWING_VERSION_MINOR 0
#define GROWING_VERSION_PATCH 0

#define GROWING_ABI_VERSION GROWING_STRINGIFY(GROWING_ABI_VERSION_NO)
#define GROWING_BEGIN_NAMESPACE \
namespace growing {           \
    inline namespace GROWING_CONCAT(v, GROWING_ABI_VERSION_NO) {
#define GROWING_END_NAMESPACE \
}                           \
}
#define GROWING_NAMESPACE growing::GROWING_CONCAT(v, GROWING_ABI_VERSION_NO)

#endif // GROWING_MACROS_H
